version: '3.6'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
      image: grafana/grafana
      depends_on:
        - prometheus
      ports:
        - 3000:3000
#      volumes:
#        - grafana_data:/var/lib/grafana
#        - ./grafana/provisioning/:/etc/grafana/provisioning/
      env_file:
        - ./grafana/config.monitoring
#      restart: always

